#!/usr/bin/env python3
"""Write the preset block of audio-transformer.sub (from xf_presets.py), the .asy symbols
of the generic subckts and every preset, and the demo schematic.

Symbols: primary coil on the left (pins at x=0), secondary on the right (pins at x=128),
core bars between, polarity dots at P1 and S1. P1/S1 at y=32, centre taps at y=80,
P2/S2 at y=128."""
from __future__ import annotations

from pathlib import Path

from xf_presets import PRESETS, subckt_text

HERE = Path(__file__).resolve().parent
SUB = HERE / "audio-transformer.sub"
MARK = "* ==== PRESETS (generated by make_symbols.py from xf_presets.py; edit there) ===="

PINS = {   # subckt -> [(name, x, y)] in SpiceOrder
    "atx": [("P1", 0, 32), ("P2", 0, 128), ("S1", 128, 32), ("S2", 128, 128)],
    "atx_sct": [("P1", 0, 32), ("P2", 0, 128), ("S1", 128, 32), ("SC", 128, 80), ("S2", 128, 128)],
    "atx_ct": [("P1", 0, 32), ("PC", 0, 80), ("P2", 0, 128), ("S1", 128, 32), ("SC", 128, 80),
               ("S2", 128, 128)],
}


def coil(x0, left):
    """Six half-turn arcs from y=32 to y=128 on the line x=x0, bulging outwards."""
    out = []
    for k in range(6):
        y = 32 + 16 * k
        if left:
            out.append(f"ARC Normal {x0 - 16} {y} {x0 + 16} {y + 16} {x0} {y} {x0} {y + 16}")
        else:
            out.append(f"ARC Normal {x0 - 16} {y} {x0 + 16} {y + 16} {x0} {y + 16} {x0} {y}")
    return out


def write_asy(name, kind, value, desc):
    L = coil(32, True) + coil(96, False)
    L += ["LINE Normal 0 32 32 32", "LINE Normal 0 128 32 128",
          "LINE Normal 96 32 128 32", "LINE Normal 96 128 128 128",
          "LINE Normal 60 24 60 136", "LINE Normal 68 24 68 136",
          "CIRCLE Normal 36 20 44 28", "CIRCLE Normal 84 20 92 28"]
    pins = PINS[kind]
    if any(p[0] == "PC" for p in pins):
        L.append("LINE Normal 0 80 32 80")
    if any(p[0] == "SC" for p in pins):
        L.append("LINE Normal 96 80 128 80")
    out = ["Version 4", "SymbolType CELL"] + L + [
        "WINDOW 0 32 -8 Left 2",
        "WINDOW 3 32 160 Left 2",
        f"SYMATTR Value {value}",
        "SYMATTR Prefix X",
        f"SYMATTR SpiceModel {name}",
        "SYMATTR ModelFile audio-transformer.sub",
        f"SYMATTR Description {desc}",
    ]
    for k, (pn, x, y) in enumerate(pins, 1):
        out += [f"PIN {x} {y} NONE 8", f"PINATTR PinName {pn}", f"PINATTR SpiceOrder {k}"]
    (HERE / f"{name}.asy").write_text("\n".join(out) + "\n")


def write_presets():
    s = SUB.read_text()
    i = s.find(MARK)
    head = s[:i] if i >= 0 else s.rstrip() + "\n\n"
    block = [MARK,
             "* Each preset takes sat (0 = linear core, the default); see xf_presets.py and",
             "* README.md \"Provenance\" for the source of every number.", "*"]
    for p in PRESETS:
        block += [subckt_text(p), ""]
    SUB.write_text(head + "\n".join(block))


# Demo: JT-115K-E in Jensen's test circuit 1: 150 ohm balanced source (75 + 75), 150 k
# load. XF_JT115KE at (256,64): P1 (256,96), P2 (256,192), S1 (384,96), S2 (384,192)
DEMO = """Version 4
SHEET 1 880 400
WIRE 64 96 112 96
WIRE 192 96 256 96
WIRE 384 96 496 96
WIRE 64 208 64 240
WIRE 64 240 112 240
WIRE 192 240 224 240
WIRE 224 240 224 192
WIRE 224 192 256 192
WIRE 64 176 64 208
WIRE 384 192 384 256
WIRE 496 176 496 256
FLAG 384 256 0
FLAG 496 256 0
FLAG 496 96 out
FLAG 64 208 0
SYMBOL voltage 64 80 R0
SYMATTR InstName V1
SYMATTR Value AC 1
SYMBOL res 208 80 R90
WINDOW 0 0 56 VBottom 2
WINDOW 3 32 56 VTop 2
SYMATTR InstName Rg1
SYMATTR Value 75
SYMBOL res 208 224 R90
WINDOW 0 0 56 VBottom 2
WINDOW 3 32 56 VTop 2
SYMATTR InstName Rg2
SYMATTR Value 75
SYMBOL XF_JT115KE 256 64 R0
SYMATTR InstName XT1
SYMATTR Value sat=0
SYMBOL res 480 80 R0
SYMATTR InstName RL
SYMATTR Value 150k
TEXT 48 312 Left 2 !.ac dec 50 1 300k
TEXT 48 344 Left 2 ;Jensen JT-115K-E in its datasheet test circuit 1 (150 ohm source, 150 k load)
"""


def main():
    write_presets()
    write_asy("atx", "atx", "n=10 Lp=5 Llk=100u Rp=20 Rs=2k Cs=100p",
              "Audio transformer, one primary, one secondary. Pins P1 P2 S1 S2")
    write_asy("atx_sct", "atx_sct", "n=2 Lp=40 Llk=10m Rp=500 Rs=1k Cs=100p",
              "Audio transformer, centre-tapped secondary. Pins P1 P2 S1 SC S2")
    write_asy("atx_ct", "atx_ct", "n=1 Lp=100 Llk=10m Rp=500 Rs=500 Cs=100p",
              "Audio transformer, centre-tapped primary and secondary. Pins P1 PC P2 S1 SC S2")
    for p in PRESETS:
        write_asy(p["name"], p["kind"], "sat=0", f"{p['desc']}. Pins " +
                  " ".join(q[0] for q in PINS[p["kind"]]))
    (HERE / "demo_audio-transformer.asc").write_text(DEMO)
    print("symbols:", ", ".join(["atx", "atx_sct", "atx_ct"] + [p["name"] for p in PRESETS]))


if __name__ == "__main__":
    main()
