#!/usr/bin/env python3
"""Write the preset block of wah-inductor.sub (from wi_presets.py), the .asy symbols of
the generic inductor and every preset, and the demo schematic.

Symbol: LTspice's inductor drawing (four half-turns, vertical) with a core bar; pins
A at (16,16) top, B at (16,112) bottom -- the same pin positions as the built-in ind."""
from __future__ import annotations

from pathlib import Path

from wi_presets import PRESETS, subckt_text

HERE = Path(__file__).resolve().parent
SUB = HERE / "wah-inductor.sub"
MARK = "* ==== PRESETS (generated by make_symbols.py from wi_presets.py; edit there) ===="


def write_asy(name, value, desc):
    L = ["LINE Normal 16 16 16 32", "LINE Normal 16 96 16 112"]
    for k in range(4):                                   # four half-turn arcs
        y = 32 + 16 * k
        L.append(f"ARC Normal 0 {y} 32 {y + 16} 16 {y + 16} 16 {y}")
    L += ["LINE Normal 40 32 40 96", "LINE Normal 44 32 44 96"]   # core
    out = ["Version 4", "SymbolType CELL"] + L + [
        "WINDOW 0 52 40 Left 2",
        "WINDOW 3 52 72 Left 2",
        f"SYMATTR Value {value}",
        "SYMATTR Prefix X",
        f"SYMATTR SpiceModel {name}",
        "SYMATTR ModelFile wah-inductor.sub",
        f"SYMATTR Description {desc}",
        "PIN 16 16 NONE 8", "PINATTR PinName A", "PINATTR SpiceOrder 1",
        "PIN 16 112 NONE 8", "PINATTR PinName B", "PINATTR SpiceOrder 2",
    ]
    (HERE / f"{name}.asy").write_text("\n".join(out) + "\n")


def write_presets():
    s = SUB.read_text()
    i = s.find(MARK)
    head = s[:i] if i >= 0 else s.rstrip() + "\n\n"
    block = [MARK,
             "* Each preset takes Qc and Cp (default 0 = not modelled); see wi_presets.py and",
             "* README.md \"Provenance\" for the source of every number.", "*"]
    for p in PRESETS:
        block += [subckt_text(p), ""]
    SUB.write_text(head + "\n".join(block))


# Demo: the inductor as a series-fed parallel LC (the Cry Baby's 0.01 uF across a red
# Fasel, fed through 100 k): V(tank) peaks at 1/(2 pi sqrt(L C)) ~ 2.1 kHz.
# WAH_RED_FASEL at (288,64): A (304,80), B (304,176)
DEMO = """Version 4
SHEET 1 760 360
WIRE 96 80 144 80
WIRE 224 80 304 80
WIRE 304 80 432 80
WIRE 96 160 96 224
WIRE 304 176 304 224
WIRE 432 144 432 224
FLAG 96 224 0
FLAG 304 224 0
FLAG 432 224 0
FLAG 304 80 tank
SYMBOL voltage 96 64 R0
SYMATTR InstName V1
SYMATTR Value AC 1
SYMBOL res 240 64 R90
WINDOW 0 0 56 VBottom 2
WINDOW 3 32 56 VTop 2
SYMATTR InstName R1
SYMATTR Value 100k
SYMBOL WAH_RED_FASEL 288 64 R0
SYMATTR InstName XL1
SYMATTR Value Qc=0 Cp=0
SYMBOL cap 416 80 R0
SYMATTR InstName C1
SYMATTR Value 10n
TEXT 72 272 Left 2 !.ac dec 200 100 20k
TEXT 72 304 Left 2 ;Dunlop red Fasel with 10 nF, fed from 100 k: V(tank) peaks near 2.1 kHz
"""


def main():
    write_presets()
    write_asy("wah_inductor", "L=500m R=17 Qc=0 Cp=0",
              "Wah inductor: L with winding resistance, optional core loss and self-capacitance. Pins A B")
    for p in PRESETS:
        write_asy(p["name"], "Qc=0 Cp=0",
                  f"{p['desc']} ({p['L'] * 1e3:g} mH, {p['R']:g} ohm). Pins A B")
    (HERE / "demo_wah-inductor.asc").write_text(DEMO)
    print("symbols:", ", ".join(["wah_inductor"] + [p["name"] for p in PRESETS]))


if __name__ == "__main__":
    main()
