#!/usr/bin/env python3
"""Write the preset block of output-transformer.sub (from ot_presets.py), the .asy
symbols of every subckt and preset, and the demo schematic.

One geometry for all, so the webapp can place any OT the same way:
  primary on the left, pins at x=0: P1 (0,16) top, CT (0,96), P2 (0,176) bottom;
      UL taps G1 (0,64), G2 (0,128) (40 % of each half from CT);
      single-ended: P (0,16), B+ (0,176)
  secondary on the right, pins at x=144: S+/S3 (144,16) top, S2 (144,80),
      S1 (144,128), S-/COM (144,176) bottom
  dots at P1 (P) and S+ (S3): those ends are in phase.
"""
from __future__ import annotations

from pathlib import Path

from ot_presets import PRESETS, pins, subckt_text

HERE = Path(__file__).resolve().parent
SUB = HERE / "output-transformer.sub"
MARK = "* ==== PRESETS (generated by make_symbols.py from ot_presets.py; edit there) ===="

# formal pin -> (x, y, shown name)
PINPOS = {"P1": (0, 16, "P1"), "G1": (0, 64, "G1"), "CT": (0, 96, "CT"), "G2": (0, 128, "G2"),
          "P2": (0, 176, "P2"), "P": (0, 16, "P"), "BP": (0, 176, "B+"),
          "SP": (144, 16, "S+"), "S3": (144, 16, "S3"), "S2": (144, 80, "S2"),
          "S1": (144, 128, "S1"), "SN": (144, 176, "S-"), "COM": (144, 176, "COM")}

BASES = {
    "ot_pp": ("Za=6600 Zs=8 P=20 Lp=25 Llk=12m Cw=300p Rpri=300 Rsec=0.5",
              "Push-pull output transformer. Pins P1 CT P2 S+ S-"),
    "ot_pp_ul": ("Za=6600 Zs=8 P=20 ul=0.4 Lp=25 Llk=12m Cw=300p Rpri=300 Rsec=0.5",
                 "Push-pull ultra-linear output transformer. Pins P1 G1 CT G2 P2 S+ S-"),
    "ot_pp_tap": ("Za=6600 Z1=4 Z2=8 Z3=16 P=20 Lp=25 Llk=12m Cw=300p Rpri=300 R1=0.3 R2=0.5 R3=0.8",
                  "Push-pull output transformer, tapped secondary. Pins P1 CT P2 COM S1 S2 S3"),
    "ot_pp_ul_tap": ("Za=6600 Z1=4 Z2=8 Z3=16 P=20 ul=0.4 Lp=25 Llk=12m Cw=300p Rpri=300 R1=0.3 R2=0.5 R3=0.8",
                     "Push-pull UL output transformer, tapped secondary. Pins P1 G1 CT G2 P2 COM S1 S2 S3"),
    "ot_se": ("Za=5000 Zs=8 P=5 Lp=15 Llk=20m Cw=300p Rpri=250 Rsec=0.5 Idc=50m",
              "Single-ended output transformer (gapped). Pins P B+ S+ S-"),
    "ot_se_tap": ("Za=5000 Z1=4 Z2=8 Z3=16 P=5 Lp=15 Llk=20m Cw=300p Rpri=250 R1=0.3 R2=0.5 R3=0.8 Idc=50m",
                  "Single-ended output transformer, tapped secondary. Pins P B+ COM S1 S2 S3"),
}


def coil(x, y0, y1, right):
    """Vertical coil on axis x from y0 to y1, 16-unit bumps bulging right or left."""
    out = []
    for y in range(y0, y1, 16):
        if right:   # counter-clockwise from bottom to top passes through the right side
            out.append(f"ARC Normal {x - 8} {y} {x + 8} {y + 16} {x} {y + 16} {x} {y}")
        else:
            out.append(f"ARC Normal {x - 8} {y} {x + 8} {y + 16} {x} {y} {x} {y + 16}")
    return out


def body(plist):
    L = []
    se = "P" in plist
    # primary coil x=48 (bulging right, towards the core), secondary x=96 (bulging left)
    L += coil(48, 16, 176, right=True)
    L += coil(96, 16, 176, right=False)
    L += ["LINE Normal 68 12 68 180", "LINE Normal 76 12 76 180"]       # core
    L += ["CIRCLE Normal 54 18 60 24", "CIRCLE Normal 84 18 90 24"]     # dots
    for pn in plist:
        x, y, shown = PINPOS[pn]
        if x == 0:
            L.append(f"LINE Normal 0 {y} 48 {y}")
            L.append(f"TEXT 4 {y - 8} Left 0 {shown}")
        else:
            L.append(f"LINE Normal 96 {y} 144 {y}")
            L.append(f"TEXT 140 {y - 8} Right 0 {shown}")
    if se:
        L.append("TEXT 24 100 Center 0 SE")
    return L


def write_asy(name, plist, value, desc):
    out = ["Version 4", "SymbolType CELL"] + body(plist) + [
        "WINDOW 0 72 -8 Center 2",
        "WINDOW 3 72 216 Center 2",
        f"SYMATTR Value {value}",
        "SYMATTR Prefix X",
        f"SYMATTR SpiceModel {name}",
        "SYMATTR ModelFile output-transformer.sub",
        f"SYMATTR Description {desc}",
    ]
    for k, pn in enumerate(plist, 1):
        x, y, shown = PINPOS[pn]
        out += [f"PIN {x} {y} NONE 8", f"PINATTR PinName {shown}", f"PINATTR SpiceOrder {k}"]
    (HERE / f"{name}.asy").write_text("\n".join(out) + "\n")


def write_presets():
    s = SUB.read_text()
    i = s.find(MARK)
    if i < 0:
        i = s.find("* ------------------------------------------------------------------------------------\n* Presets:")
    head = s[:i] if i >= 0 else s.rstrip() + "\n\n"
    block = [MARK,
             "* Hammond Mfg. replacement / catalogue output transformers. Sheet numbers and",
             "* their sources: ot_presets.py and README.md \"Provenance\". Sheets:",
             "* https://www.hammfg.com/files/parts/pdf/<PART>.pdf (fetched 2026-09-14).",
             "* Lp here = sheet L corrected for Cw (the sheet's L is an apparent value at 1 kHz",
             "* or 60 Hz); Cw and some Llk fitted to the sheet's response graph (fit_presets.py).",
             "* Each preset takes sat, fsat, ksat, Qc as parameters (defaults shown).",
             "*"]
    for p in PRESETS:
        block += [subckt_text(p), ""]
    SUB.write_text(head + "\n".join(block))


DEMO = """Version 4
SHEET 1 880 400
WIRE 64 112 96 112
WIRE 176 112 256 112
WIRE 64 192 64 272
WIRE 64 272 96 272
WIRE 176 272 256 272
WIRE 400 176 464 176
WIRE 464 256 464 272
WIRE 400 272 464 272
FLAG 256 192 0
FLAG 400 272 0
FLAG 400 176 out
SYMBOL voltage 64 96 R0
SYMATTR InstName V1
SYMATTR Value SINE(0 200 100) AC 1
SYMBOL res 192 96 R90
SYMATTR InstName R1
SYMATTR Value 3300
SYMBOL res 192 256 R90
SYMATTR InstName R2
SYMATTR Value 3300
SYMBOL OT_1760H 256 96 R0
SYMATTR InstName XOT
SYMATTR Value sat=1
SYMBOL res 448 160 R0
SYMATTR InstName RL
SYMATTR Value 8
TEXT 40 336 Left 2 !.ac dec 20 10 100k
TEXT 40 368 Left 2 ;Deluxe Reverb OT (Hammond 1760H) driven plate-to-plate from Rs = Za, 8 ohm on the 8-ohm tap
"""


def main():
    write_presets()
    for name, (value, desc) in BASES.items():
        write_asy(name, pins(name), value, desc)
    for p in PRESETS:
        write_asy(p["name"], pins(p["base"]), f"sat=1 fsat={p['fsat']:g}",
                  f"{p['amp']} (Hammond {p['part']}). Pins "
                  + " ".join(PINPOS[q][2] for q in pins(p["base"])))
    (HERE / "demo_output-transformer.asc").write_text(DEMO)
    print("symbols:", ", ".join(list(BASES) + [p["name"] for p in PRESETS]))


if __name__ == "__main__":
    main()
