#!/usr/bin/env python3
"""Write the preset block of speaker.sub (from spk_presets.py), the .asy symbols of the
generic speaker and every preset, and the demo schematic.

Symbol: the usual loudspeaker drawing (magnet box + cone) facing right; pins on the
left: P (+) at (0,32), N at (0,96)."""
from __future__ import annotations

from pathlib import Path

from spk_presets import PRESETS, subckt_text

HERE = Path(__file__).resolve().parent
SUB = HERE / "speaker.sub"
MARK = "* ==== PRESETS (generated by make_symbols.py from spk_presets.py; edit there) ===="


def write_asy(name, value, desc):
    L = ["RECTANGLE Normal 16 40 32 88",
         "LINE Normal 32 40 64 8", "LINE Normal 64 8 64 120", "LINE Normal 64 120 32 88",
         "LINE Normal 0 32 16 32", "LINE Normal 16 32 16 40",
         "LINE Normal 0 96 16 96", "LINE Normal 16 96 16 88",
         "TEXT 4 24 Left 0 +"]
    out = ["Version 4", "SymbolType CELL"] + L + [
        "WINDOW 0 72 32 Left 2",
        "WINDOW 3 72 96 Left 2",
        f"SYMATTR Value {value}",
        "SYMATTR Prefix X",
        f"SYMATTR SpiceModel {name}",
        "SYMATTR ModelFile speaker.sub",
        f"SYMATTR Description {desc}",
        "PIN 0 32 NONE 8", "PINATTR PinName P", "PINATTR SpiceOrder 1",
        "PIN 0 96 NONE 8", "PINATTR PinName N", "PINATTR SpiceOrder 2",
    ]
    (HERE / f"{name}.asy").write_text("\n".join(out) + "\n")


def write_presets():
    s = SUB.read_text()
    i = s.find(MARK)
    head = s[:i] if i >= 0 else s.rstrip() + "\n\n"
    block = [MARK,
             "* Each preset takes Vb (closed box, 0 = free air) and n; see spk_presets.py and",
             "* README.md \"Provenance\" for the source of every number.", "*"]
    for p in PRESETS:
        block += [subckt_text(p), ""]
    SUB.write_text(head + "\n".join(block))


# Demo: a speaker on a 1 V source with 8 ohm output resistance (a valve amp without
# feedback is ~ its load impedance; a solid-state amp ~0): V(spk) shows the impedance.
# SPK_V30_16 at (256,64): P (256,96), N (256,160)
DEMO = """Version 4
SHEET 1 700 320
WIRE 64 96 112 96
WIRE 192 96 256 96
WIRE 64 176 64 208
WIRE 256 160 256 208
FLAG 64 208 0
FLAG 256 208 0
FLAG 256 96 spk
SYMBOL voltage 64 80 R0
SYMATTR InstName V1
SYMATTR Value AC 1
SYMBOL res 208 80 R90
SYMATTR InstName Ro
SYMATTR Value 8
SYMBOL SPK_V30_16 256 64 R0
SYMATTR InstName XSPK
SYMATTR Value Vb=0 n=0.7
TEXT 40 256 Left 2 !.ac dec 50 10 20k
TEXT 40 288 Left 2 ;Celestion Vintage 30 16 ohm on a 1 V source with 8 ohm output resistance
"""


def main():
    write_presets()
    write_asy("speaker", "Re=6.4 Fs=80 Qms=5 Qes=1 Le=0.7m n=0.7",
              "Loudspeaker impedance from Thiele-Small parameters. Pins P N")
    for p in PRESETS:
        write_asy(p["name"], "Vb=0 n=0.7",
                  f"{p['maker']} {p['name'][4:]} speaker impedance ({p['ohm']} ohm). Pins P N")
    (HERE / "demo_speaker.asc").write_text(DEMO)
    print("symbols:", ", ".join(["speaker"] + [p["name"] for p in PRESETS]))


if __name__ == "__main__":
    main()
