#!/usr/bin/env python3
"""Write the preset block of guitar-pickup.sub (from pu_presets.py), the .asy symbols of
the generic pickup and every preset, and the demo schematic.

Symbol: a pickup bobbin (rectangle with six pole pieces) with the coil lead-outs on the
right: OUT at (96,32), GND at (96,96); the string-signal input EMF on the left at (0,64).
SpiceOrder OUT GND EMF, as in the subckt."""
from __future__ import annotations

from pathlib import Path

from pu_presets import PRESETS, subckt_text

HERE = Path(__file__).resolve().parent
SUB = HERE / "guitar-pickup.sub"
MARK = "* ==== PRESETS (generated by make_symbols.py from pu_presets.py; edit there) ===="


def write_asy(name, value, desc):
    L = ["RECTANGLE Normal 16 40 80 88"]
    for k in range(6):                        # pole pieces
        x = 22 + 10 * k
        L.append(f"CIRCLE Normal {x} 60 {x + 8} 68")
    L += ["LINE Normal 80 48 96 48", "LINE Normal 96 48 96 32",      # OUT lead
          "LINE Normal 80 80 96 80", "LINE Normal 96 80 96 96",      # GND lead
          "LINE Normal 0 64 16 64",                                  # EMF input
          "TEXT 84 24 Left 0 +",
          "TEXT 2 56 Left 0 emf"]
    out = ["Version 4", "SymbolType CELL"] + L + [
        "WINDOW 0 16 0 Left 2",
        "WINDOW 3 16 120 Left 2",
        f"SYMATTR Value {value}",
        "SYMATTR Prefix X",
        f"SYMATTR SpiceModel {name}",
        "SYMATTR ModelFile guitar-pickup.sub",
        f"SYMATTR Description {desc}",
        "PIN 96 32 NONE 8", "PINATTR PinName OUT", "PINATTR SpiceOrder 1",
        "PIN 96 96 NONE 8", "PINATTR PinName GND", "PINATTR SpiceOrder 2",
        "PIN 0 64 NONE 8", "PINATTR PinName EMF", "PINATTR SpiceOrder 3",
    ]
    (HERE / f"{name}.asy").write_text("\n".join(out) + "\n")


def write_presets():
    s = SUB.read_text()
    i = s.find(MARK)
    head = s[:i] if i >= 0 else s.rstrip() + "\n\n"
    block = [MARK,
             "* Each preset takes kx (eddy-damped fraction of L); see pu_presets.py and",
             "* README.md \"Provenance\" for the source of every number.", "*"]
    for p in PRESETS:
        block += [subckt_text(p), ""]
    SUB.write_text(head + "\n".join(block))


# Demo: a 1972 Stratocaster pickup driven by a 100 mV AC "string" EMF, into a 250 k
# volume pot (full up), a 3 m cable (~330 pF, Zollner 9.4: ~100 pF/m) and a 1 Meg amp
# input. V(out) shows the pickup + cable resonance.
# PU_STRAT72 at (224,64): OUT (320,96), GND (320,160), EMF (224,128)
DEMO = """Version 4
SHEET 1 880 400
WIRE 128 128 224 128
WIRE 320 96 432 96
WIRE 432 96 544 96
WIRE 544 96 656 96
WIRE 128 208 128 240
WIRE 320 160 320 240
WIRE 432 176 432 240
WIRE 544 160 544 240
WIRE 656 176 656 240
FLAG 128 240 0
FLAG 320 240 0
FLAG 432 240 0
FLAG 544 240 0
FLAG 656 240 0
FLAG 656 96 out
SYMBOL voltage 128 112 R0
SYMATTR InstName Vstr
SYMATTR Value SINE(0 0.1 440) AC 0.1
SYMBOL PU_STRAT72 224 64 R0
SYMATTR InstName XPU
SYMATTR Value kx=0.5
SYMBOL res 416 80 R0
SYMATTR InstName Rvol
SYMATTR Value 250k
SYMBOL cap 528 96 R0
SYMATTR InstName Ccable
SYMATTR Value 330p
SYMBOL res 640 80 R0
SYMATTR InstName Ramp
SYMATTR Value 1Meg
TEXT 96 296 Left 2 !.ac dec 50 20 20k
TEXT 96 328 Left 2 ;1972 Stratocaster pickup (Lemme), 250 k volume pot, 3 m cable, 1 Meg amp input
"""


def main():
    write_presets()
    write_asy("pickup", "L=2.5 R=6k C=110p Rx=500k kx=0.5",
              "Magnetic guitar pickup: EMF-driven coil with eddy loss, DCR, winding C. Pins OUT GND EMF")
    for p in PRESETS:
        write_asy(p["name"], f"kx={p['kx']:g}",
                  f"{p['desc']} pickup (L {p['L']:g} H, R {p['R'] / 1e3:g}k). Pins OUT GND EMF")
    (HERE / "demo_guitar-pickup.asc").write_text(DEMO)
    print("symbols:", ", ".join(["pickup"] + [p["name"] for p in PRESETS]))


if __name__ == "__main__":
    main()
